### ISSUE TITLE
Monero CI problems

### ISSUE THREAD

**Issue by UkoeHB** [tevador/mx25519#6]
There are a number of compile errors on different architectures that are getting caught by Monero CI.

Here ([A](https://github.com/UkoeHB/monero/actions/runs/2929827470), [B](https://github.com/UkoeHB/monero/actions/runs/2929827468)) is a recent run on my `seraphis_lib` branch.

**Comment by tevador** [comment]
A) `error: ‘struct sp::jamtis::jamtis_mock_keys’ has no member named ‘K_ua’; did you mean ‘xK_ua’?` etc. Unless I'm missing something, these errors don't seem to be related to mx25519.

B) The i686 build should be fixed by cd798e0c136d53f5c9989ad41fb3365a2ae559c3
The MacOS aarch64 build has a separate issue #7
